version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/cloudwatch.yml:/etc/prometheus/cloudwatch.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Admin1234
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

  cloudwatch_exporter:
    image: prom/cloudwatch-exporter:latest
    container_name: cloudwatch_exporter
    ports:
      - "9106:9106"
    volumes:
      - ./prometheus/cloudwatch.yml:/config/config.yml
    restart: unless-stopped

volumes:
  grafana_data:
